language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip setuptools
install:
  - pip install cython numpy scipy
  - python setup.py install --cython
script:
  - py.test test
