language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-numpy python-scipy python3-numpy python3-scipy
install:
  - sudo pip install cython
  - sudo python setup.py install --cython
script:
  - py.test test
