language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - libatlas-base-dev
before_install:
  - pip install -U pip setuptools pytest
  - pip install -U cython
  - travis_wait pip install scipy
install:
  - travis_wait python setup.py install --cython
script:
  - py.test src/scs/test
  - py.test --pyargs scs
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
