language: python
sudo: false
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - python-numpy
    - python-scipy
    - python3-numpy
    - python3-scipy
    #- libatlas3-base
    #- libatlas-base-dev (this one really messed up by boxs)
before_install:
  - pip install -U pip setuptools
  - pip install cython
install:
  - python setup.py install --cython
script:
  - py.test test
